language: node_js
node_js:
  - "4.1"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "QJJ/zGnIFJz5/k02KrjSCFQge0H6PeSfkJqAndtaGGZRnY8I+ONDbFUxc5lSzECv5f0eWn/GGXzFNUUEX8qd7shAoVlQPY+zzzncsYjABo73o4wHv4RdWlw45oAtO8gExt5PHD/i29gJ2Wp4flLvrPQcutnBDUktpYbmf5us0PvIDHjz/urRzpxzvGIo+d+6zwJuxewvGecurZTFRl1cfFfKKEq7BnfZLAFM4coz+3pdryaVBw7V4WvMYdXv5/xet4hVPb63zj1u8MU/eP7D8Kp5+QDj1pYjWBiI+wC6g2zTzMohsIWGlAucTN3+9Ele9fSJbwaz3XwH5XVzIbcQuLd8GJZLwVDv/a7ePBnawowRlbYofMsgW/gH2YpKau1olgZBtvEx8CsAFjjzSfv0/cBwgu64USwg9Uj/Z+PamBugBPfPp36CD4llhNWENFcCVA8K+Eg0HycjCHp0su9iUCnmgAkLEAQZz2FwAf30nozOjXNn7z9KC5uJh9osnHvagXfYBkz2dYzCl7ORxxssKDEtPVG3Kg1jVSbVYejarLuAFzKrrxBSsBITVvm/VYPNoOQprOcs7PWeP89xwFZRrbksnuweJXhSvN42EuguEEZk/I4LinTTuy1QN2h8vNSzMhWLknfU24gyHHuoVC9Yq2bW878zFJszltB4JCiS4Es="

# whitelist
branches:
  only:
    - master
    - dev
    - ran-test

before_script:
  - jekyll build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 20 # give xvfb some time to start

script:
  - ./node_modules/karma/bin/karma start karma.conf.js
#  - htmlproof ./_site --verbose --href-ignore "#" --disable-external --file-ignore './_site/node_modules/*'
# - jekyll serve &
# - sleep 20 # give jekyll some time to start
# - galen test tests/galen/all.test --htmlreport tests/galen/reports/all
# - jekyll serve & #refresh jekyll
# - sleep 5
# - galen test tests/galen/all-part2.test --htmlreport tests/galen/reports/all-part2

#  - galen test tests/galen/all.test --htmlreport tests/galen/reports/all -groups SupportPage,ProductsDocsConsole,PD-WidgetsPage,Events
#  - galen test tests/galen/generate-img-all.test --htmlreport tests/galen/reports/all --groups SupportPage,ProductsDocsConsole,ProductsDocsSlate,PD-WidgetsPage,BlogsPage,Events,PartnersNexus,PartnersLanding,PD-getting-started-Page #generate comparing images
#  - galen test tests/galen/generate-img-all.test --htmlreport tests/galen/reports/all --groups PartnersNexus,PartnersLanding #generate comparing images

after_script:
  - rake travis:deploy --trace --verbose
  - rake travis:report --trace --verbose

cache:
  directories:
    - node_modules
    - bundler

notifications:
  email: false #

before_install:
  - ls ./
  - rm ./_site/* -rf #remove directory _site
  - rm ./events/* -rf #remove directory events
  - rm ./partners/* -rf #remove directory partners
  - \cp -avrf ./tests/content/*/ ./ #copy test content
  - ls ./events/list
  - rvm install 2.1.5
  - gem install github-pages
  - gem install html-proofer
  - npm install -g galenframework-cli
