language: node_js
node_js:
  - "4.1"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "S0LPAFWXDLDDDzBLh2ptfxUNUvE4q6gEWTuS2TCiq8ZAoeR9jwMKQuT5scAKqQeKSjEWfTXdNJRKuvwKsruWfYLtXz4yoMjPz7/WMmJLedRLp9nh7lIJP7/p/Fs3zJwMYE/twvOlnNUXCSQaL7FMefrvXf52Tn34i3edRTsx2x0ALGHEcj+nv7ISCN7+IAOC4C2Fyc0UXZ8KQECtHIJ94ZXrbMRWKR2tYeVsa9Z4QVIXBzQ+ku64t4ccQvw/mFAj/qqrys0+ayF1sWjvU3Nn8mfiuB1OZdrpJ5dwNE5LEm/CbJIl2hYbwhGXa23FtZr1mLQeNChzcKffk9TR+xYk6s2ndYkLdgeSX9GM71DPk0d3NEXWfugL2Hcf585W5gjdY2WIoJO6cHGrcsGmJ7dHAr2XwDD0wuO7Vqdkk6rCxLjFnJ3MJtGNwjDujxtrlXTuR/K4vI+sMB4fKCfIFZfDJHYCqh2bcQnOQJchlWR80AAkbJ1ApbE3uuFS7sgCHjyqJI49MyWAjCRTfyhtLvj37KaCEZTZht2Ye27sR/6P4qruPfHCU8DbH5bAYd4IZ5QPWzsSgO3Y9y6yUh5k21fcIjfQ+CR+Sjp1D5Ck8ycwNJcHiUVX0yjLjK4ZJT/zJ8A87hNACyjKJMtyer7DqW2d9cmACPBqHT4lMOdaTKEz/sU="

# whitelist
branches:
  only:
    - master
    - dev

script:
  - ./node_modules/karma/bin/karma start karma.conf.js
  - htmlproof ./_site --verbose --href-ignore "#" --disable-external --file-ignore './_site/node_modules/*'
# - galen check galen-test/home.gspec --url http://ticketmaster-api.github.io/ --size 1024x768 --htmlreport tests/galen/reports -Dphantomjs.binary.path=/usr/local/phantomjs/bin/phantomjs


after_script:
  - rake travis:deploy --trace --verbose

cache:
  directories:
    - node_modules
    - bundler

notifications:
  email: false

before_install:
  - rvm install 2.1.5
  - gem install jekyll
  - gem install html-proofer
  - npm install -g galenframework-cli

    