language: node_js
node_js:
  - "4.1"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "Vm2fPb3xYfgs2DPyILWt509v+yrMyXxX+xDbckmHAwPg7Qnwz8KIfrTveHDZhNn9ImD1QvzRWxRYBYs6VfmV/Pc3xy+YeVtQzYdsAwUDhOHNg2WEmkUTn8FhP2aHzEUHyMNeSQvQonuQCMdc1jiqHaSGwYlWK/9EMyyOh0/1+yyE/gzuqVNhDhoHHaTjlpdkjz40zi2/LtKAs/cK8ex8OWONtnkzY9oikYgEU9b1xNqOi7j1C2ZtpFz3RN3FzRJfKpf2CDfMWE8mqZscHzog3/Z9KGz39SCXwN11qQRFUA9sE5x9wv1emyU9+68x7+T6Ml+tro2QiVvfLZFJ9PBVMnROKtLHiek6to2dLm+i0HSd7MNk9xiBRjxoUYN/Rpb70obZkDvZtcouc1kpuOG845AZAjuJchBZyHMcQ9OSmw7DGiHLptjliXoksGF941zXqrWaZIWkah5FPmlPcnvuxVYs2evWHUeoZWhdlCO5DA/PhlmnN72JD/m1KmNzNyhqpXaJN8zA2zXtQjdei96CLr4bKwGtZ59Vws5kVZkQfobmPXtKza6ODyqveMe0mWTCG50WMGn+FiP+1SaDDqbsd9gK94m7P1pez7hX7KxgL2NDZBtBBacTTkIe+EbBmaY58/QVDNdGoIml0HU6MZSlBaOnXvnJb2pjSqLDm8Wuqxg="

# whitelist
branches:
  only:
    - master
    - dev

script:
  - ./node_modules/karma/bin/karma start karma.conf.js
  - htmlproof ./_site --verbose --href-ignore "#" --disable-external --file-ignore './_site/node_modules/*'
# - galen check galen-test/home.gspec --url http://ticketmaster-api.github.io/ --size 1024x768 --htmlreport tests/galen/reports -Dphantomjs.binary.path=/usr/local/phantomjs/bin/phantomjs


after_script:
  - rake travis:deploy --trace --verbose

cache:
  directories:
    - node_modules
    - bundler

notifications:
  email: false

before_install:
  - rvm install 2.1.5
  - gem install jekyll
  - gem install html-proofer
  - npm install -g galenframework-cli

    